version: '3.8'

services:
  api:
    build: ..
    container_name: dwaarpal-api
    restart: always
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      - PORT=8080
      - REDIS_ADDRESS=redis-cluster:7010,redis-cluster:7011,redis-cluster:7012,redis-cluster:7013,redis-cluster:7014,redis-cluster:7015
      - REDIS_TIMEOUT_MS=1000
    depends_on:
      - redis-cluster
  redis-cluster:
    image: grokzen/redis-cluster:latest
    container_name: dwaarpal-redis-cluster
    environment:
      - INITIAL_PORT=7010
      - IP=redis-cluster
    ports:
      - "7010:7010"
      - "7011:7011"
      - "7012:7012"
      - "7013:7013"
      - "7014:7014"
      - "7015:7015"

  prometheus:
    image: prom/prometheus:latest
    container_name: dwaarpal-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: dwaarpal-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
