// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: api/proto/ratelimit.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckRateLimitRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// The algorithm to use: "TOKEN_BUCKET", "FIXED_WINDOW", or "SLIDING_WINDOW"
	Algorithm string `protobuf:"bytes,2,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	// Maximum number of allowed requests
	Limit int32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	// Window size in seconds
	Window        int32 `protobuf:"varint,4,opt,name=window,proto3" json:"window,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRateLimitRequest) Reset() {
	*x = CheckRateLimitRequest{}
	mi := &file_api_proto_ratelimit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRateLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRateLimitRequest) ProtoMessage() {}

func (x *CheckRateLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_ratelimit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRateLimitRequest.ProtoReflect.Descriptor instead.
func (*CheckRateLimitRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_ratelimit_proto_rawDescGZIP(), []int{0}
}

func (x *CheckRateLimitRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CheckRateLimitRequest) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *CheckRateLimitRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *CheckRateLimitRequest) GetWindow() int32 {
	if x != nil {
		return x.Window
	}
	return 0
}

type CheckRateLimitResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Allowed   bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Remaining int32                  `protobuf:"varint,2,opt,name=remaining,proto3" json:"remaining,omitempty"`
	// Retry after in milliseconds
	RetryAfter int64 `protobuf:"varint,3,opt,name=retry_after,json=retryAfter,proto3" json:"retry_after,omitempty"`
	// Timestamp for when the limit resets (ISO 8601 string format)
	ResetAt       string `protobuf:"bytes,4,opt,name=reset_at,json=resetAt,proto3" json:"reset_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRateLimitResponse) Reset() {
	*x = CheckRateLimitResponse{}
	mi := &file_api_proto_ratelimit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRateLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRateLimitResponse) ProtoMessage() {}

func (x *CheckRateLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_ratelimit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRateLimitResponse.ProtoReflect.Descriptor instead.
func (*CheckRateLimitResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_ratelimit_proto_rawDescGZIP(), []int{1}
}

func (x *CheckRateLimitResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckRateLimitResponse) GetRemaining() int32 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

func (x *CheckRateLimitResponse) GetRetryAfter() int64 {
	if x != nil {
		return x.RetryAfter
	}
	return 0
}

func (x *CheckRateLimitResponse) GetResetAt() string {
	if x != nil {
		return x.ResetAt
	}
	return ""
}

var File_api_proto_ratelimit_proto protoreflect.FileDescriptor

const file_api_proto_ratelimit_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/ratelimit.proto\x12\tratelimit\"u\n" +
	"\x15CheckRateLimitRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1c\n" +
	"\talgorithm\x18\x02 \x01(\tR\talgorithm\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06window\x18\x04 \x01(\x05R\x06window\"\x8c\x01\n" +
	"\x16CheckRateLimitResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x1c\n" +
	"\tremaining\x18\x02 \x01(\x05R\tremaining\x12\x1f\n" +
	"\vretry_after\x18\x03 \x01(\x03R\n" +
	"retryAfter\x12\x19\n" +
	"\breset_at\x18\x04 \x01(\tR\aresetAt2k\n" +
	"\x12RateLimiterService\x12U\n" +
	"\x0eCheckRateLimit\x12 .ratelimit.CheckRateLimitRequest\x1a!.ratelimit.CheckRateLimitResponseB/Z-github.com/prathamkhanduja/dwaarpal/api/protob\x06proto3"

var (
	file_api_proto_ratelimit_proto_rawDescOnce sync.Once
	file_api_proto_ratelimit_proto_rawDescData []byte
)

func file_api_proto_ratelimit_proto_rawDescGZIP() []byte {
	file_api_proto_ratelimit_proto_rawDescOnce.Do(func() {
		file_api_proto_ratelimit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_ratelimit_proto_rawDesc), len(file_api_proto_ratelimit_proto_rawDesc)))
	})
	return file_api_proto_ratelimit_proto_rawDescData
}

var file_api_proto_ratelimit_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_ratelimit_proto_goTypes = []any{
	(*CheckRateLimitRequest)(nil),  // 0: ratelimit.CheckRateLimitRequest
	(*CheckRateLimitResponse)(nil), // 1: ratelimit.CheckRateLimitResponse
}
var file_api_proto_ratelimit_proto_depIdxs = []int32{
	0, // 0: ratelimit.RateLimiterService.CheckRateLimit:input_type -> ratelimit.CheckRateLimitRequest
	1, // 1: ratelimit.RateLimiterService.CheckRateLimit:output_type -> ratelimit.CheckRateLimitResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_ratelimit_proto_init() }
func file_api_proto_ratelimit_proto_init() {
	if File_api_proto_ratelimit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_ratelimit_proto_rawDesc), len(file_api_proto_ratelimit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_ratelimit_proto_goTypes,
		DependencyIndexes: file_api_proto_ratelimit_proto_depIdxs,
		MessageInfos:      file_api_proto_ratelimit_proto_msgTypes,
	}.Build()
	File_api_proto_ratelimit_proto = out.File
	file_api_proto_ratelimit_proto_goTypes = nil
	file_api_proto_ratelimit_proto_depIdxs = nil
}
