syntax = "proto3";

package ratelimit;

option go_package = "github.com/prathamkhanduja/dwaarpal/api/proto";

service RateLimiterService {
    rpc CheckRateLimit (CheckRateLimitRequest) returns (CheckRateLimitResponse);
}

message RateLimitDescriptor {
    string key = 1;
    string algorithm = 2; 
    int32 limit = 3;
    int32 window = 4; 
}

message CheckRateLimitRequest {
    repeated RateLimitDescriptor descriptors = 1;
}

message CheckRateLimitResponse {
    bool allowed = 1;
    string failed_key = 2;
    int32 remaining = 3;
    int64 retry_after = 4; 
    string reset_at = 5; 
}
